# Generated by Django 2.1.5 on 2019-01-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_id', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
